# train: /export/c04/jiatong/project/ai_system/CALL-proto/data/train_960.ali
# val: /export/c04/jiatong/project/ai_system/CALL-proto/data/dev_960.ali
train: /export/c04/jiatong/project/ai_system/CALL-proto/data/debug.ali
val: /export/c04/jiatong/project/ai_system/CALL-proto/data/debug.ali

model_save_dir: exp/debug_gaussian
model_type: Transformer
max_epochs: 2
lr: 0.01
optimizer: noam
max_len: 100
batchsize: 64
num_workers: 4

phone_size: 87
dim_feedforward: 128
embedding_size: 64
hidden_size: 64
num_block: 2
nhead: 4
local_gaussian: True
