train: /export/c04/jiatong/project/ai_system/CALL-proto/data/train_960.ali
val: /export/c04/jiatong/project/ai_system/CALL-proto/data/dev_960.ali


model_save_dir: exp/debug
model_type: Transformer
max_epochs: 50
lr: 0.01
optimizer: noam
max_len: 100
batchsize: 64
num_workers: 4

phone_size: 87
dim_feedforward: 1024
embedding_size: 256
hidden_size: 256
num_block: 6
nhead: 4

